### PR TITLE
Fixing network error in ios

### LINKED ISSUE #34: Red screen of death: Network request failed
In iOS, and don't know if android as well, when we don't have connectivity or it drops, we show a red screen of death with a horrible react native message.

### PR DESCRIPTION
**Pull request by arcturus**
Fixes #34

### CODE REVIEW

**Comment by arcturus** [comment]
I've discovered that `console.error` in iOS shows you the read screen of death, thing that doesn't happen in Android.

I've just replaced the console.error for console.info, and also setup a listener for displaying the error message on the visual component using the scanner.

@wilsonpage will you take a look? Do you like the prompt with the info or do you prefer a silent action?

File: lib/scanner/index.js [hunk 1]
```diff
@@ -156,7 +157,18 @@ class Scanner {
         this.callback(data);
       })
 
-      .catch(err => console.error(err));
+      .catch(err => {
+        console.info(err);
+        if (this.netErrorListener) {
+          this.netErrorListener(err);
```
Comment (wilsonpage) [inline lib/scanner/index.js:167]: Should we check if the error is network related? Currently this could be any error.

File: lib/scanner/index.js [hunk 2]
```diff
@@ -156,7 +157,18 @@ class Scanner {
...
+        }
+      });
+  }
+
+  set networkErrorListener(cb) {
```
Comment (wilsonpage) [inline lib/scanner/index.js]: Never seen this syntax before. Is there a reason for it?

File: lib/views/list.js [hunk 3]
```diff
@@ -30,6 +31,9 @@ class List extends Component {
 
     this.onItemLongPress = this.onItemLongPress.bind(this);
     this.scanner = new Scanner(this.onItemFound.bind(this));
+    this.scanner.networkErrorListener = () => {
+      Alert.alert('Network error', 'Please check your internet connection');
+    };
```
Comment (wilsonpage) [inline lib/views/list.js]: For consistency we should probably pass all callbacks into the constructor.

``` js
new Scanner({
  onItemFound: ...,
  onNetworkError: ...
});
```

File: lib/scanner/index.js (hunk 2 above)
Comment (wilsonpage) [inline lib/scanner/index.js]: Ah I get it now. See [comment](https://github.com/mozilla-magnet/magnet/pull/39/files#r60883335)

File: lib/views/list.js (hunk 3 above)
Comment (arcturus) [inline lib/views/list.js]: Makes sense

File: lib/scanner/index.js (hunk 1 above)
Comment (arcturus) [inline lib/scanner/index.js:167]: Yes, that's a good point, let's check for the network error

File: lib/scanner/index.js [hunk 4]
```diff
@@ -156,7 +157,13 @@ class Scanner {
         this.callback(data);
       })
 
-      .catch(err => console.error(err));
+      .catch(err => {
+        console.info(err);
+        if (['NetworkError', 'TypeError'].indexOf(err.name)
```
Comment (arcturus) [inline lib/scanner/index.js]: We are also receiving a TypeError: Network error message in some cases, so I added both to the list of error problems.

File: lib/views/list.js [hunk 5]
```diff
@@ -29,7 +30,9 @@ class List extends Component {
     };
 
     this.onItemLongPress = this.onItemLongPress.bind(this);
-    this.scanner = new Scanner(this.onItemFound.bind(this));
+    this.scanner = new Scanner(this.onItemFound.bind(this), () => {
+      Alert.alert('Network error', 'Please check your internet connection');
+    });
```
Comment (wilsonpage) [inline lib/views/list.js:38]: NIT: Would prefer this as a named options object. Otherwise I don't know what the second argument is for without reading the implementation of `Scanner`.

File: lib/scanner/index.js (hunk 4 above)
Comment (wilsonpage) [inline lib/scanner/index.js]: Are you missing `> -1` ?
